#!/bin/bash
# ============================================================
# InvoiceText installer (universal)
# (c) 2025 Carsten Hilbert - MIT License
# ============================================================
# Creates a small launcher "m" in ~/.local/bin that calls
# the project-specific make.py from the current directory.
# ============================================================

set -e

echo "🧰 Installing InvoiceText launcher..."

# Detect OS
TARGET="$HOME/.local/bin"
mkdir -p "$TARGET"

# Determine project path (the current folder where install.sh lives)
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
MAKE_FILE="$PROJECT_DIR/make.py"
LAUNCHER="$TARGET/m"

# Check for make.py
if [ ! -f "$MAKE_FILE" ]; then
  echo "❌ make.py not found in project folder: $PROJECT_DIR"
  echo "Please make sure this script is next to make.py."
  exit 1
fi

# Write launcher file
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# ------------------------------------------------------------
# Launcher for InvoiceText
# Automatically generated by install.sh
# ------------------------------------------------------------
python3 "$MAKE_FILE" "\$@"
EOF

# Make launcher executable
chmod +x "$LAUNCHER"

echo "✅ Installed successfully!"
echo ""
echo "The command 'm' is now available globally."
echo ""
echo "Try:"
echo "  m i1     → generate invoice"
echo "  m e2     → generate estimate"
echo ""
echo "If it doesn't work immediately, restart your terminal."
